apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-gateway
  template:
    metadata:
      labels:
        app: fastapi-gateway
    spec:
      containers:
      - name: fastapi-gateway
        image: crisbid/fastapi-gateway:latest
        env:
          - name: RABBITMQ_HOST
            value: rabbitmq
          - name: RABBITMQ_PORT
            value: "5672"
          - name: RABBITMQ_USER
            value: user
          - name: RABBITMQ_PASSWORD
            value: password
          - name: SECRET_KEY
            value: "secret"
        ports:
        - containerPort: 8000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-auth
  template:
    metadata:
      labels:
        app: fastapi-auth
    spec:
      initContainers:
        - name: wait-for-cassandra
          image: busybox
          command: ['sh', '-c', 'until nc -z cassandra 9042; do echo waiting for cassandra; sleep 5; done;']
      containers:
      - name: fastapi-auth
        image: crisbid/fastapi-auth:latest
        env:
          - name: RABBITMQ_HOST
            value: rabbitmq
          - name: RABBITMQ_PORT
            value: "5672"
          - name: RABBITMQ_USER
            value: user
          - name: RABBITMQ_PASSWORD
            value: password
          - name: SECRET_KEY
            value: "secret"
          - name: CASSANDRA_HOST
            value: cassandra
          - name: CASSANDRA_USER
            value: admin
          - name: CASSANDRA_PASSWORD
            value: admin123
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-transacao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-transacao
  template:
    metadata:
      labels:
        app: fastapi-transacao
    spec:
      initContainers:
        - name: wait-for-cassandra
          image: busybox
          command: ['sh', '-c', 'until nc -z cassandra 9042; do echo waiting for cassandra; sleep 5; done;']
      containers:
      - name: fastapi-transacao
        image: crisbid/fastapi-transacao:latest
        env:
          - name: RABBITMQ_HOST
            value: rabbitmq
          - name: RABBITMQ_PORT
            value: "5672"
          - name: RABBITMQ_USER
            value: user
          - name: RABBITMQ_PASSWORD
            value: password
          - name: SECRET_KEY
            value: "secret"
          - name: CASSANDRA_HOST
            value: cassandra
          - name: CASSANDRA_USER
            value: admin
          - name: CASSANDRA_PASSWORD
            value: admin123
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-bdupdate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-bdupdate
  template:
    metadata:
      labels:
        app: fastapi-bdupdate
    spec:
      initContainers:
        - name: wait-for-cassandra
          image: busybox
          command: ['sh', '-c', 'until nc -z cassandra 9042; do echo waiting for cassandra; sleep 5; done;']
      containers:
      - name: fastapi-bdupdate
        image: crisbid/fastapi-bdupdate:latest
        env:
          - name: RABBITMQ_HOST
            value: rabbitmq
          - name: RABBITMQ_PORT
            value: "5672"
          - name: RABBITMQ_USER
            value: user
          - name: RABBITMQ_PASSWORD
            value: password
          - name: SECRET_KEY
            value: "secret"
          - name: CASSANDRA_HOST
            value: cassandra
          - name: CASSANDRA_USER
            value: admin
          - name: CASSANDRA_PASSWORD
            value: admin123
        ports:
        - containerPort: 8000