apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-gateway
  template:
    metadata:
      labels:
        app: fastapi-gateway
    spec:
      containers:
      - name: fastapi-gateway
        image: crisbid/fastapi-gateway:latest
        env:
          - name: RABBITMQ_HOST
            value: rabbitmq
          - name: RABBITMQ_PORT
            value: "5672"
          - name: RABBITMQ_USER
            value: user
          - name: RABBITMQ_PASSWORD
            value: password
          - name: SECRET_KEY
            value: "secret"
          - name: CASSANDRA_HOST
            value: "179.189.94.124"
        ports:
        - containerPort: 8000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-auth
  template:
    metadata:
      labels:
        app: fastapi-auth
    spec:
      containers:
      - name: fastapi-auth
        image: crisbid/fastapi-auth:latest
        env:
          - name: RABBITMQ_HOST
            value: rabbitmq
          - name: RABBITMQ_PORT
            value: "5672"
          - name: RABBITMQ_USER
            value: user
          - name: RABBITMQ_PASSWORD
            value: password
          - name: SECRET_KEY
            value: "secret"
          - name: CASSANDRA_HOST
            value: "179.189.94.124"
          #- name: CASSANDRA_USER
          #  value: admin
          #- name: CASSANDRA_PASSWORD
          #  value: admin123
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-transacao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-transacao
  template:
    metadata:
      labels:
        app: fastapi-transacao
    spec:
      containers:
      - name: fastapi-transacao
        image: crisbid/fastapi-transacao:latest
        env:
          - name: RABBITMQ_HOST
            value: rabbitmq
          - name: RABBITMQ_PORT
            value: "5672"
          - name: RABBITMQ_USER
            value: user
          - name: RABBITMQ_PASSWORD
            value: password
          - name: SECRET_KEY
            value: "secret"
          - name: CASSANDRA_HOST
            value: "179.189.94.124"
          #- name: CASSANDRA_USER
          #  value: admin
          #- name: CASSANDRA_PASSWORD
          #  value: admin123
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-chavepix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-chavepix
  template:
    metadata:
      labels:
        app: fastapi-chavepix
    spec:
      containers:
      - name: fastapi-chavepix
        image: crisbid/fastapi-chavepix:latest
        env:
          - name: RABBITMQ_HOST
            value: rabbitmq
          - name: RABBITMQ_PORT
            value: "5672"
          - name: RABBITMQ_USER
            value: user
          - name: RABBITMQ_PASSWORD
            value: password
          - name: SECRET_KEY
            value: "secret"
          - name: CASSANDRA_HOST
            value: "179.189.94.124"
          #- name: CASSANDRA_USER
          #  value: admin
          #- name: CASSANDRA_PASSWORD
          #  value: admin123
        ports:
        - containerPort: 8000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-usuario
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-usuario
  template:
    metadata:
      labels:
        app: fastapi-usuario
    spec:
      containers:
      - name: fastapi-usuario
        image: crisbid/fastapi-usuario:latest
        env:
          - name: RABBITMQ_HOST
            value: rabbitmq
          - name: RABBITMQ_PORT
            value: "5672"
          - name: RABBITMQ_USER
            value: user
          - name: RABBITMQ_PASSWORD
            value: password
          - name: SECRET_KEY
            value: "secret"
          - name: CASSANDRA_HOST
            value: "179.189.94.124"
          #- name: CASSANDRA_USER
          #  value: admin
          #- name: CASSANDRA_PASSWORD
          #  value: admin123
        ports:
        - containerPort: 8000