apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management
spec:
  type: NodePort
  ports:
    - port: 15672
      targetPort: 15672
      nodePort: 31672  # Porta externa
  selector:
    app: rabbitmq
