apiVersion: v1
kind: Service
metadata:
  name: fastapi-gateway
spec:
  type: NodePort
  selector:
    app: fastapi-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30000

---

apiVersion: v1
kind: Service
metadata:
  name: fastapi-auth
spec:
  type: NodePort
  selector:
    app: fastapi-auth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30100

---

apiVersion: v1
kind: Service
metadata:
  name: fastapi-transacao
spec:
  type: NodePort
  selector:
    app: fastapi-transacao
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30200

---

apiVersion: v1
kind: Service
metadata:
  name: fastapi-chavepix
spec:
  type: NodePort
  selector:
    app: fastapi-chavepix
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30300